const Map<String, String> ar = {
  // ===== Authentication =====
  // ===== Login Screen =====
  'Welcome Back!': 'مرحبًا بعودتك!',
  'Login with your email or phone and password':
      'سجّل الدخول باستخدام البريد الإلكتروني أو الهاتف وكلمة المرور',
  'Email or Phone': 'البريد الإلكتروني أو الهاتف',
  'Enter your email or phone': 'أدخل البريد الإلكتروني أو رقم الهاتف',
  'Enter Password': 'أدخل كلمة المرور',
  'Forget Password?': 'نسيت كلمة المرور؟',
  'Don\'t have account?': 'ليس لديك حساب؟',
  'Create New': 'أنشئ حسابًا جديدًا',
  'This field is required': 'هذا الحقل مطلوب',
  'Home Page': 'الصفحة الرئيسية',
  'Logged in successfully!': 'تم تسجيل الدخول بنجاح!',
  'Login': 'تسجيل الدخول',
  'Password': 'كلمة المرور',

  // ===== Role Selection =====
  'Join as a Client or Service Provider': 'انضم كعميل أو كمقدم خدمة',
  'I\'m a Client': 'أنا عميل',
  'Looking for help with a project.': 'أبحث عن مساعدة في مشروع.',
  'I\'m a Service Provider': 'أنا مقدم خدمة',
  'Looking for my favorite work.': 'أبحث عن عملي المفضل.',
  'Create Account': 'إنشاء حساب',
  'Already have an account?': 'هل لديك حساب بالفعل؟',
  'Close': 'إغلاق',

  // ===== SignUp Screen 1 =====
  'Create New Account': 'إنشاء حساب جديد',
  'Step 1 of 2': 'الخطوة 1 من 2',
  'Step 2 of 2': 'الخطوة 2 من 2',
  'Full Name': 'الاسم الكامل',
  'Email': 'البريد الإلكتروني',
  'Enter your email': 'أدخل بريدك الإلكتروني',
  //'Password': 'كلمة المرور',
  'Uploading image is optional': 'رفع الصورة اختياري',
  'I Accept  ': 'أوافق على ',
  'Terms & Conditions': 'الشروط والأحكام',
  'Next': 'التالي',
  "please_select_country": "يرجى اختيار الدولة أولاً",
  "without_country_code": "بدون كود الدولة",
  "phone": "رقم الهاتف",
  "digits": "أرقام",
  "loading": "جارٍ التحميل...",
  "country": "الدولة",
  "city": "المدينة",
  "provider_type": "نوع المزود",
  "customer": "عميل",
  "provider": "مزود الخدمة",
  "select_country": "اختر الدولة",
  "select_city": "اختر المدينة",
  "bio": "نبذة عن الشركة",
  "bio_hint": "وصف مختصر عن الشركة",
  "value_added_tax": "ضريبة القيمة المضافة (VAT)",
  "value_added_tax_hint": "أضف الرقم هنا",
  "commercial_register_number": "رقم السجل التجاري",
  "commercial_register_number_hint": "أضف الرقم هنا",
  "tax_number": "الرقم الضريبي",
  "tax_number_hint": "أضف الرقم هنا",
  "commercial_register": "السجل التجاري",
  "commercial_register_hint": "لم يتم اختيار ملف",
  "tax_card": "البطاقة الضريبية",
  "tax_card_hint": "لم يتم اختيار ملف",
  "menu": "القائمة",
  "personal_information": "المعلومات الشخصية",
  "phone_number": "رقم الهاتف",
  "email": "البريد الإلكتروني",
  "location": "الموقع",
  //"country": "الدولة",
  "other_services": "خدمات أخرى",
  "edit_profile": "تعديل الملف الشخصي",
  "change_password": "تغيير كلمة المرور",
  "remove_account": "حذف الحساب",
  "logout": "تسجيل الخروج",
  "about_us": "من نحن",
  "terms_conditions": "الشروط والأحكام",
  "change_language": "تغيير اللغة",
  "english": "الإنجليزية",
  "arabic": "العربية",
  'home': 'الرئيسية',
  'shop': 'المتجر',
  'posts': 'المنشورات',
  'jobs': 'الوظائف',
  //'menu': 'القائمة',
  'logout_title': 'تسجيل الخروج',
  'logout_message': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'logout_yes': 'نعم',
  'logout_no': 'لا',
  "delete_title": "إزالة الحساب",
  "delete_message": "هل أنت متأكد أنك تريد إزالة حسابك؟.",
  "delete_yes": "نعم ",
  "delete_no": "لا",
  // "jobs": "الوظائف",
  "orders": "الطلبات",
  // "posts": "المنشورات",
  "complaints": "الشكاوى",
};
