const Map<String, String> en = {
  // ===== Authentication =====
  // ===== Login Screen =====
  'Welcome Back!': 'Welcome Back!',
  'Login with your email or phone and password':
      'Login with your email or phone and password',
  'Email or Phone': 'Email or Phone',
  'Enter your email or phone': 'Enter your email or phone',
  'Enter Password': 'Enter Password',
  'Forget Password?': 'Forget Password?',
  'Don\'t have account?': 'Don\'t have account?',
  'Create New': 'Create New',
  'This field is required': 'This field is required',
  'Home Page': 'Home Page',
  'Logged in successfully!': 'Logged in successfully!',
  'Login': 'Login',
  'Password': 'Password',

  // ===== Role Selection =====
  'Join as a Client or Service Provider':
      'Join as a Client or Service Provider',
  'I\'m a Client': 'I\'m a Client',
  'Looking for help with a project.': 'Looking for help with a project.',
  'I\'m a Service Provider': 'I\'m a Service Provider',
  'Looking for my favorite work.': 'Looking for my favorite work.',
  'Create Account': 'Create Account',
  'Already have an account?': 'Already have an account?',
  'Close': 'Close',

  // ===== SignUp Screen 1 =====
  'Create New Account': 'Create New Account',
  'Step 1 of 2': 'Step 1 of 2',
  'Step 2 of 2': 'Step 2 of 2',
  'Full Name': 'Full Name',
  'Email': 'Email',
  'Enter your email': 'Enter your email',
  //'Password': 'Password',
  'Uploading image is optional': 'Uploading image is optional',
  'I Accept  ': 'I Accept  ',
  'Terms & Conditions': 'Terms & Conditions',
  'Next': 'Next',
  "please_select_country": "Please select a country first",
  "without_country_code": "Without country code",
  "phone": "Phone",
  "digits": "digits",
  "loading": "Loading...",
  "country": "Country",
  "city": "City",
  "provider_type": "Provider Type",
  "customer": "Customer",
  "provider": "Provider",
  "select_country": "Select Country",
  "select_city": "Select City",
  "bio": "Bio",
  "bio_hint": "Description of the company",
  "value_added_tax": "Value Added Tax (VAT)",
  "value_added_tax_hint": "Add the number here",
  "commercial_register_number": "Commercial Register Number",
  "commercial_register_number_hint": "Add the number here",
  "tax_number": "Tax Number",
  "tax_number_hint": "Add the number here",
  "commercial_register": "Commercial Register",
  "commercial_register_hint": "No File Selected",
  "tax_card": "Tax Card",
  "tax_card_hint": "No File Selected",
  "menu": "Menu",
  "personal_information": "Personal Information",
  "phone_number": "Phone Number",
  "email": "Email",
  "location": "Location",
  // "country": "Country",
  "other_services": "Other Services",
  "edit_profile": "Edit Profile",
  "change_password": "Change Password",
  "remove_account": "Remove Account",
  "logout": "Logout",
  "about_us": "About us",
  "terms_conditions": "Terms & Conditions",
  "change_language": "Change Language",
  "english": "English",
  "arabic": "Arabic",
  'home': 'Home',
  'shop': 'Shop',
  'posts': 'Posts',
  'jobs': 'Jobs',
  'logout_title': 'Logout',
  'logout_message': 'Are you sure you want to logout?',
  'logout_yes': 'Yes',
  'logout_no': 'No',
  "delete_title": "Remove Account",
  "delete_message": "Are you sure you want to remove your account?.",
  "delete_yes": "Yes",
  "delete_no": "No",
  // "jobs": "Jobs",
  "orders": "Orders",
  // "posts": "Posts",
  "complaints": "Complaints",
  //'menu': 'Menu',
};
